### ISSUE TITLE
Implement toString()

### ISSUE THREAD

**Issue by johnjohndoe** [jonfhancock/JsonToJava#2]
It would be helpful if you could also generate the `toString()` method for each model class. It should output the values for each member variable. Here is an example:

``` java
@Override
public String toString() {
    return "deg = " + mDeg + ", gust = " + mGust + ", speed = " + mSpeed;
}
```

In the UI you can add an option to let the user decide whether the method should be generated.

**Comment by jonfhancock** [comment]
Thanks for the suggestion!  I'll work on that.

**Comment by jonfhancock** [comment]
Done!  Also deployed the change to App Engine.

**Comment by johnjohndoe** [comment]
Nice. Though I have to say, I tested it with the [OpenWeatherMap API](http://api.openweathermap.org/data/2.5/weather?lat=47.663267&lon=-122.384187) and it does not generate `toString()` methods for all classes and does not include all members.
