### ISSUE TITLE
Cannot run in tomcat, when click download button, prompts 404

### ISSUE THREAD

**Issue by crazier9527** [jonfhancock/JsonToJava#5]
Cannot run in tomcat, when click download button, prompts 404

**Comment by jonfhancock** [comment]
Interesting. I hadn't thought about running it on tomcat.  I only built it to run on AppEngine. 

Can you tell me a little about the urls it is returning, and any debug information that could be helpful?

**Comment by crazier9527** [comment]
Has solved, after I clone project, I saw the web project. I out of curiosity ran:)
